apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alf.io-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: postgresql-95-centos7
  name: postgresql-95-centos7
spec:
  replicas: 1
  selector:
    app: postgresql-95-centos7
    deploymentconfig: postgresql-95-centos7
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: postgresql-95-centos7
        deploymentconfig: postgresql-95-centos7
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: alfio
        - name: POSTGRESQL_PASSWORD
          value: 237vnaw8zevbaacwzebt
        - name: POSTGRESQL_USER
          value: alfy
        image: centos/postgresql-95-centos7
        imagePullPolicy: Always
        name: postgresql-95-centos7
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: volume-qp85f
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: volume-qp85f
        persistentVolumeClaim:
          claimName: alf.io-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-95-centos7
  name: postgresql-95-centos7
spec:
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgresql-95-centos7
    deploymentconfig: postgresql-95-centos7
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: alfio
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'alfio:latest'
  source:
    git:
      ref: openshift_1.x-maintenance
      uri: 'https://github.com/vorburger/alf.io'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 's2i-java:latest'
    type: Source
