apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alf.io-db
  namespace: alf-io
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: postgresql-95-centos7
  name: postgresql-95-centos7
  namespace: alf-io
spec:
  replicas: 1
  selector:
    app: postgresql-95-centos7
    deploymentconfig: postgresql-95-centos7
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: postgresql-95-centos7
        deploymentconfig: postgresql-95-centos7
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: alfio
        - name: POSTGRESQL_PASSWORD
          value: 237vnaw8zevbaacwzebt
        - name: POSTGRESQL_USER
          value: alfy
        image: centos/postgresql-95-centos7
        imagePullPolicy: Always
        name: postgresql-95-centos7
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: volume-qp85f
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: volume-qp85f
        persistentVolumeClaim:
          claimName: alf.io-db
